# Norsk Media example: 12_smooth_switcher
#
# Switch smoothly between two sources
#

version: "3"

services:
  norsk:
    container_name: norsk-server
    image: norskvideo/norsk:v0.0.328-main
    network_mode: host
    volumes:
      - ${LICENSE_FILE}:/mnt/license.json:ro
      - ${LOG_ROOT}:/var/log/norsk
    command: --license-file /mnt/license.json
    shm_size: '2gb'
    # cpuset: "0-15"
  example:
    container_name: norsk-example-app
    build:
      context: examples
      dockerfile: Dockerfile
      network: host # note this is for build only, not at runtime. Without it npm install can fail on some systems
    network_mode: host
    depends_on:
      norsk:
        condition: service_healthy
    command: node -e 'require("./lib/src/12_smooth_switcher").main()'
  source_0:
    container_name: norsk-source_0
    image: datarhei/ffmpeg
    network_mode: host
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        sleep 1
        ffmpeg -v error -re -f lavfi -i "testsrc[out0];sine=frequency=220:sample_rate=48000[out1]" -vcodec h264 -b:v 150000 -b:a 5000 -vf scale=1280:720 -aspect 1280:720 -x264opts "keyint=25:min-keyint=25:no-scenecut:bframes=0" -bluray-compat true -tune stillimage -pix_fmt yuv420p -acodec aac -metadata language=en -f mpegts -flush_packets 0 'srt://127.0.0.1:5001'
    depends_on:
      - example
  source_1:
    container_name: norsk-source_1
    image: datarhei/ffmpeg
    network_mode: host
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        sleep 1
        ffmpeg -v error -re -f lavfi -i "testsrc[out0];sine=frequency=275:sample_rate=48000[out1]" -vcodec h264 -b:v 150000 -b:a 5000 -vf scale=1280:720 -aspect 1280:720 -x264opts "keyint=25:min-keyint=25:no-scenecut:bframes=0" -bluray-compat true -tune stillimage -pix_fmt yuv420p -acodec aac -metadata language=en -f mpegts -flush_packets 0 'srt://127.0.0.1:5002'
    depends_on:
      - example
