# Norsk Media example: 20_audio_mixer
#
# Mix a chord from audio generators and publish it in an audio-only HLS playlist
#

version: "3"

services:
  norsk:
    container_name: norsk-server
    image: norskvideo/norsk:v1.0.332-main
    network_mode: host
    volumes:
      - ${LICENSE_FILE}:/mnt/license.json:ro
      - ${LOG_ROOT}:/var/log/norsk
    command: --license-file /mnt/license.json 
    shm_size: '2gb'
    # cpuset: "0-15"
  example:
    container_name: norsk-example-app
    build:
      context: examples
      dockerfile: Dockerfile
      network: host # note this is for build only, not at runtime. Without it npm install can fail on some systems
    network_mode: host
    environment:
      - PUBLIC_URL_PREFIX=${PUBLIC_URL_PREFIX}
      - DEBUG_URL_PREFIX=${DEBUG_URL_PREFIX}
    depends_on:
      norsk:
        condition: service_healthy
    command: node -e 'require("./lib/src/20_audio_mixer").main()'
  source:
    container_name: norsk-source
    image: datarhei/ffmpeg
    network_mode: host
    entrypoint: ["/bin/sh","-c"]
    volumes:
      - ./examples/data:/tmp/data:ro
    command:
    - |
        sleep 1
        
    depends_on:
      - example
