# Norsk Media example: 16_compose_smooth
#
# Another picture in picture example, with smooth transitions between compositions
#

version: "3.5"

networks:
  norskNetwork:
    name: norsk-nw

services:
  norsk:
    container_name: norsk-server
    image: norskvideo/norsk:v0.0.330-main
    ports:
      - 5001:5001/tcp # For RTMP sources
      - 5001:5001/udp # For SRT sources
      - 6790:6790/tcp # GRPC interface
      - 6791:6791/tcp # Debugging endpoints, including the workflow visualizer, logs, and docs
      - 8080:8080/tcp # Public endpoints for HLS/DASH and WebRTC players
    volumes:
      - ${LICENSE_FILE}:/mnt/license.json:ro
      - ${LOG_ROOT}:/var/log/norsk
      
    command: --license-file /mnt/license.json 
    shm_size: '2gb'
    # cpuset: "0-15"
    networks:
      - norskNetwork
  example:
    container_name: norsk-example-app
    build:
      context: examples
      dockerfile: Dockerfile
      network: host # note this is for build only, not at runtime. Without it npm install can fail on some systems
    environment:
      - NORSK_HOST=norsk
    depends_on:
      norsk:
        condition: service_healthy
    command: node -e 'require("./lib/src/16_compose_smooth").main()'
    networks:
      - norskNetwork
  source_0:
    container_name: norsk-source_0
    image: datarhei/ffmpeg
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        sleep 1
        ffmpeg -v error -re -f lavfi -i "testsrc[out0];sine=frequency=220:sample_rate=48000[out1]" -vcodec h264 -b:v 150000 -b:a 20000 -vf scale=1280:720 -aspect 1280:720 -x264opts "keyint=25:min-keyint=25:no-scenecut:bframes=0" -bluray-compat true -tune stillimage -pix_fmt yuv420p -acodec aac -metadata language=en -f mpegts -flush_packets 0 'srt://norsk:5001'
    depends_on:
      - example
    networks:
      - norskNetwork
  source_1:
    container_name: norsk-source_1
    image: datarhei/ffmpeg
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        sleep 1
        ffmpeg -v error -re -f lavfi -i "rgbtestsrc[out0];sine=frequency=275:sample_rate=48000[out1]" -vcodec h264 -b:v 150000 -b:a 20000 -vf scale=1280:720 -aspect 1280:720 -x264opts "keyint=25:min-keyint=25:no-scenecut:bframes=0" -bluray-compat true -tune stillimage -pix_fmt yuv420p -acodec aac -metadata language=en -f flv 'rtmp://norsk:5002/acme/high'
    depends_on:
      - example
    networks:
      - norskNetwork
